### ISSUE TITLE
JavaDoc

### ISSUE THREAD

**Issue by Axel94** [tpe-lecture/group-10#2]
@return sollte Rückgabetyp angeben, da man sonst von außerhalb nicht sehen kann welcher Datentyp zurückgegeben wird.

**Comment by JesusJones92** [comment]
Rückgabetyp ist auch ohne JavaDoc ersichtlich. Dennoch wäre es natürlich schöner, diesen anzugeben.

**Comment by JesusJones92** [comment]
Laut Oracle Dokumentation lautet die Syntax für @return "@return  description". Der Rückgabetyp wird hier nicht verlangt und  nicht benötigt.
